name: "My Composite Action"
description: "Execute awesome steps"
inputs:
  name:
    required: true
    default: "world"
outputs:
  time:
    value: ${{ steps.now.outputs.time }}
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.name }}.
      shell: bash

    - id: now
      run: echo "::set-output name=time::$(date +%s)"
      shell: bash
