name: call-workflo-dispatch

on:
  workflow_dispatch:

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: gh workflow run workflow-dispatch.yml -f stringValue=foo -f booleanValue=true -f envValue=develop
