name: custom-action-composite

on:
  workflow_dispatch:

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: hello
        uses: ./custom-action/composite
        with:
          name: "lambdasawa"

      - run: echo "${{ steps.hello.outputs.time }}"
