name: environment-develop

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ secrets.MY_SECRET }} | sha256sum
