name: github-script

on:
  workflow_dispatch:

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: script
        uses: actions/github-script@v6
        with:
          script: return require('./github-script/hello.js')({ github, context });
          result-encoding: string
        env:
          REF: "${{ github.ref }}"

      - run: echo "${{ steps.script.outputs.result }}"
