
name: Hello, world!

on:
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-22.04
    steps:
      - run: echo '# foo' >> $GITHUB_STEP_SUMMARY

      - run: echo '# bar' >> $GITHUB_STEP_SUMMARY
