name: merge-to-main

on:
  workflow_dispatch:

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}

      - run: |
          set -xeuo pipefail

          ts="$(date +%s)"
          echo "$ts" > timestamp

          git checkout -b "update-timestamp-$ts"

          git config user.name github-actions
          git config user.email github-actions@github.com

          git add timestamp
          git commit -m "Update timestamp"
          git push -u origin "update-timestamp-$ts"

          gh pr create -f
          gh pr merge --squash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
