name: push-to-main

on:
  workflow_dispatch:

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          set -xeuo pipefail

          ts="$(date +%s)"
          echo "$ts" > timestamp

          git config user.name github-actions
          git config user.email github-actions@github.com

          git add timestamp
          git commit -m "Update timestamp"
          git push origin main
